# Dependabot configuration:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    ignore:
      # depends on kotlin-stdlib ABI,
      # which is bundled with and determined by Gradle
      - name: io.ktor:ktor-server-cio
      - name: io.ktor:ktor-client-cio
      - name: com.diffplug.spotless:com.diffplug.spotless.gradle.plugin
    schedule:
      interval: "daily"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
